AGS_VERBOSE_MAP = {
    "PROJ": "Project Information",
    "ABBR": "Abbreviation Definitions",
    "DICT": "User Defined Groups and Headings",
    "FILE": "Associated Files",
    "TRAN": "Data File Transmission Information / Data Status",
    "TYPE": "Definition of Data Types",
    "UNIT": "Definition of Units",
    "CLSS": "Classification tests",
    "CONG": "Consolidation Tests - General",
    "CONS": "Consolidation Tests - Data",
    "CORE": "Coring Information",
    "GEOL": "Field Geological Descriptions",
    "GRAG": "Particle Size Distribution Analysis - General",
    "GRAT": "Particle Size Distribution Analysis - Data",
    "SCPG": "Static Cone Penetration Tests - General",
    "SCPT": "Static Cone Penetration Tests - Data",
    "SCPP": "Static Cone Penetration Tests - Derived Parameters",
    "LOCA": "Location Details",
    "DETL": "Stratum Detail Descriptions",
    "SAMP": "Sample Information",
    "GCHM": "Geotechnical Chemistry Testing",
    "LDEN": "Density tests",
    "LLPL": "Liquid and Plastic Limit Tests",
    "LNMC": "Water/Moisture Content Tests",
    "LPDN": "Particle Density Tests",
    "LPEN": "Laboratory Hand Penetrometer Tests",
    "TREG": "Triaxial Tests - Effective Stress - General",
    "TRET": "Triaxial Tests - Effective Stress - Data",
    "TRIG": "Triaxial Tests - Total Stress - General",
    "TRIT": "Triaxial Tests - Total Stress - Data",
    "GRAD": "Particle size distribution data",
    "RELD": "Relative density test",
    "STCN": "Static cone penetration test",
}
